rumus = ("Konversi dolar ke rupiah")
p = input("Masukkan nilai panjang kurs Dollar =")
k = input("Masukkan nilai jumlah dollar =")
pi=int(p)
ki=int(k)
Konversi = (pi*ki)
print()
print("===========================================================================================================")
print("Konversi dolar ke rupiah dengan nilai panjang kurs Dollar = " +p+ " dan nilai jumlah dollar5 = " +k+ " adalah sebesar "+str(Konversi)+".-")
print("===========================================================================================================")
