rumus = ("Menghitung Volume Prisma Segitiga")
a = input("Masukkan alas segitiga =")
t = input("Masukkan tinggi segitiga =")
s = input("Masukkan tinggi prisma =")
ai=int(a)
ti=int(t)
si=int(s)
Volume = (1/2*ai*ti*si)
print()
print("==================")
print("Perhitungan volume prisma segitiga dengan alas segitiga = "+a+" dan tinggi segitiga = "+t+" serta tinggi prisma = "+s+" adalah sebesar "+str(Volume)+" m3 ")
print("==================")
